### ISSUE TITLE
Incompatible with recent stable mkdocs 1.1

### ISSUE THREAD

**Issue by Voronenko** [fmaida/mkdocs-blog-plugin#1]
Starting from latest release 1.1 mkdocs has dropped support for py2, and thus it no longer has definition for string_types , etc used in plugin configuration

```
PY3 = sys.version_info[0] == 3

if PY3:                         # pragma: no cover
    string_types = str,         # noqa
    text_type = str             # noqa
else:                           # pragma: no cover
    string_types = basestring,  # noqa
    text_type = unicode      
```

**Comment by fmaida** [comment]
Thank you for reporting that. I'll try to fix it ASAP.

**Comment by fmaida** [comment]
Sorry for being late, I just removed any reference to the utils.string_types and replaced it with str. 
I didn't make a lot of tests after fixing this issue, but I see that my two example blogs do compile and work now. I just pushed these fixes in version 0.25 to PyPi FYI.

Thanks for having reported this issue.

**Comment by Voronenko** [comment]
Thanks a lot. Happy Easter !

**Comment by fmaida** [comment]
Thanks. Happy easter to you as well.
